### ISSUE TITLE
Add support for Travis CI

### ISSUE THREAD

**Issue by jueti** [jueti/HUGIS#4]
#### Quick Start

Travis CI supports Python language. Here is a short introduction: [Building a Python Project - Travis CI](https://docs.travis-ci.com/user/languages/python/)

#### Integrations

**Coveralls**

Methods to integrate: [Coveralls - Travis CI](https://docs.travis-ci.com/user/coveralls/)

Coveralls for Python: [Python | Coveralls Docs](https://docs.coveralls.io/python)
* ~~[python-coveralls](https://github.com/z4r/python-coveralls) by Andrea De Marco~~ out of dates
* [coveralls-python](https://github.com/coveralls-clients/coveralls-python) by Ilya Baryshev

an `.travis.yml` example:
```yaml
language: python
install:
  - pip install coveralls
script:
  - export PYTHONPATH=$PWD; coverage run --source='.' manage.py test
  - export PYTHONPATH=$PWD; coverage run --source='.' -a hugis/wsgi.py
  - coverage report -m
after_success:
  - coveralls
```

once you do a commit, a travis ci build process will run automatically.
but before committing,  run a coverage on your host machine first.
```powershell
(venv) PS> pipenv install coverage --dev
(venv) PS> $env:PYTHONPATH=$pwd; coverage run --source='.' .\manage.py test
(venv) PS> $env:PYTHONPATH=$pwd; coverage run --source='.' -a  .\hugis\wsgi.py
(venv) PS> coverage report -m
```

if you got 90+ percents, you are supposed to commit.
otherwise, write more tests to increase coverage.

_Originally posted by @jueti in https://github.com/jueti/HUGIS/issues/2#issuecomment-477229584_

**Comment by jueti** [comment]
Oops, travis ci build task has been queued for ten minutes.
I searched for a solution, and found this: travis-ci/travis-ci#8354

I looked over my subscription.
The trial includes **100 trial builds and 2-concurrent-jobs**.

my old `.travis.yml`:
```yml
dist: xenial
language: python
python:
  - "3.7"
  - "3.7-dev"
  - "3.8-dev"
install:
  - pip install coveralls
script:
  - export PYTHONPATH=$PWD; coverage run --source='.' manage.py test
  - export PYTHONPATH=$PWD; coverage run --source='.' -a hugis/wsgi.py
  - coverage report -m
after_success:
  - coveralls
```
This generate 3 jobs and result in a long time to queue.
