### ISSUE TITLE
Fix travis ci build tasks taked long time to queue

### ISSUE THREAD

**Issue by jueti** [jueti/HUGIS#5]
Oops, travis ci build task has been queued for ten minutes.
I searched for a solution, and found this: travis-ci/travis-ci#8354

I looked over my subscription.
The trial includes **100 trial builds and 2-concurrent-jobs**.

my old `.travis.yml`:
```yml
dist: xenial
language: python
python:
  - "3.7"
  - "3.7-dev"
  - "3.8-dev"
install:
  - pip install coveralls
script:
  - export PYTHONPATH=$PWD; coverage run --source='.' manage.py test
  - export PYTHONPATH=$PWD; coverage run --source='.' -a hugis/wsgi.py
  - coverage report -m
after_success:
  - coveralls
```
This generate 3 jobs and result in a long time to queue.

_Originally posted by @jueti in https://github.com/jueti/HUGIS/issues/4#issuecomment-477279179_
