### ISSUE TITLE
Add support for Codecov

### ISSUE THREAD

**Issue by jueti** [jueti/HUGIS#7]
Add support for Codecov

Base on this example: [codecov/example-python: Python coverage example](https://github.com/codecov/example-python)

add the following line to `.travis.yml`
```yml
install:
  - pip install codecov
after_success:
  - codecov
```

_Originally posted by @jueti in https://github.com/jueti/HUGIS/issues/2#issuecomment-477394715_
